# Generated by Django 4.1.2 on 2022-11-02 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mensage',
            new_name='sage',
        ),
    ]
