# Generated by Django 4.1.2 on 2022-11-02 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wp', '0002_rename_mensage_sage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sage',
            new_name='Mensage',
        ),
    ]
