# Generated by Django 4.1.2 on 2022-10-28 19:42

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact Phone', max_length=31)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
