# Generated by Django 4.1.2 on 2022-10-28 21:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.PositiveBigIntegerField(help_text='DD-XXXX XXXX sem os espaços e sem o nove adicional', validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
