# Generated by Django 4.1.2 on 2022-10-31 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_empresa_tipolaudo_remove_person_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='whatsapp',
        ),
    ]
