# Generated by Django 4.1.2 on 2022-10-31 19:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_empresa_rename_phone_person_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='telefone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='whatsapp',
            field=models.PositiveBigIntegerField(default=1, help_text='DD-XXXX XXXX sem os espaços e sem o nove adicional', unique=True, validators=[django.core.validators.MaxValueValidator(9999999999)]),
            preserve_default=False,
        ),
    ]
