# Generated by Django 4.1.2 on 2022-10-31 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_alter_person_whatsapp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='whatsapp',
            new_name='phone',
        ),
    ]
