# Generated by Django 4.1.2 on 2022-11-01 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_laudo_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laudo',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='laudo',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='laudo',
            name='name',
        ),
        migrations.RemoveField(
            model_name='laudo',
            name='tipo',
        ),
    ]
