# Generated by Django 4.1.2 on 2022-11-01 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_remove_laudo_cliente_remove_laudo_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laudo',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.tipolaudo'),
        ),
    ]
