# Generated by Django 4.1.2 on 2022-11-01 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0011_laudo_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laudo',
            name='tipo',
        ),
    ]
