# Generated by Django 4.1.2 on 2022-11-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0012_remove_laudo_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='laudo',
            name='tipo',
            field=models.CharField(choices=[('CIV', 'CIV'), ('CIPP', 'CIPP')], default=1, max_length=4),
            preserve_default=False,
        ),
    ]
