# Generated by Django 4.1.2 on 2022-11-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0013_laudo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laudo',
            name='dataValidade',
            field=models.DateField(verbose_name='%d/%m/%Y'),
        ),
    ]
