# Generated by Django 4.1.2 on 2022-11-01 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0014_alter_laudo_datavalidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laudo',
            name='dataValidade',
            field=models.DateField(),
        ),
    ]
