# Generated by Django 4.1.2 on 2022-11-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0015_alter_laudo_datavalidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laudo',
            name='numero',
            field=models.IntegerField(unique=True),
        ),
    ]
