# Generated by Django 4.1.2 on 2022-11-02 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0019_alter_laudo_cliente_alter_laudo_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='laudo',
            name='dataLaudo',
            field=models.DateField(default='2002-02-02'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laudo',
            name='placa',
            field=models.CharField(default='', help_text='formato XXX-XXXX', max_length=8),
            preserve_default=False,
        ),
    ]
