# Generated by Django 4.1.2 on 2022-11-03 00:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0020_laudo_datalaudo_laudo_placa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='whatsapp',
            field=models.PositiveBigIntegerField(help_text='DD-9XXXX XXXX sem os espaços', unique=True, validators=[django.core.validators.MaxValueValidator(99999999999)]),
        ),
    ]
